name: CI/CD for Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Node.js Application
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x


      - name: Install Dependencies
        run: npm install


      - name: Build the App
        run: npm run build


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ci-cd-tutorial:latest

  deploy:
    name: Deploy Docker Image to EC2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Docker Image to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ci-cd-tutorial:latest
            sudo docker stop ci-cd-tutorial || true
            sudo docker rm ci-cd-tutorial || true
            sudo docker run -d --name ci-cd-tutorial -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/ci-cd-tutorial:latest
